package com.ted.resonance.entity;

import java.math.BigDecimal;
import java.util.Date;

public class AddressMinBalanceBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_min_balance.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_min_balance.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_min_balance.day_time
     *
     * @mbggenerated
     */
    private Date dayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_min_balance.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_min_balance.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_min_balance.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_min_balance.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_min_balance.id
     *
     * @return the value of address_min_balance.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_min_balance.id
     *
     * @param id the value for address_min_balance.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_min_balance.address
     *
     * @return the value of address_min_balance.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_min_balance.address
     *
     * @param address the value for address_min_balance.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_min_balance.day_time
     *
     * @return the value of address_min_balance.day_time
     *
     * @mbggenerated
     */
    public Date getDayTime() {
        return dayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_min_balance.day_time
     *
     * @param dayTime the value for address_min_balance.day_time
     *
     * @mbggenerated
     */
    public void setDayTime(Date dayTime) {
        this.dayTime = dayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_min_balance.balance
     *
     * @return the value of address_min_balance.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_min_balance.balance
     *
     * @param balance the value for address_min_balance.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_min_balance.create_time
     *
     * @return the value of address_min_balance.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_min_balance.create_time
     *
     * @param createTime the value for address_min_balance.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_min_balance.update_time
     *
     * @return the value of address_min_balance.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_min_balance.update_time
     *
     * @param updateTime the value for address_min_balance.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_min_balance.del
     *
     * @return the value of address_min_balance.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_min_balance.del
     *
     * @param del the value for address_min_balance.del
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }
}