package com.ted.resonance.entity;

import java.util.Date;

public class BroadcastTransactionBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broadcast_transaction.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broadcast_transaction.ref_id
     *
     * @mbggenerated
     */
    private Integer refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broadcast_transaction.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broadcast_transaction.v
     *
     * @mbggenerated
     */
    private Integer v;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broadcast_transaction.r
     *
     * @mbggenerated
     */
    private String r;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broadcast_transaction.s
     *
     * @mbggenerated
     */
    private String s;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broadcast_transaction.signed_data
     *
     * @mbggenerated
     */
    private String signedData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broadcast_transaction.status
     * <p>
     * 0 初始化；1 未广播交易；2 广播交易成功 ；3 广播交易失败;4 已达到足够确认数
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broadcast_transaction.tx_hash
     *
     * @mbggenerated
     */
    private String txHash;

    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broadcast_transaction.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broadcast_transaction.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broadcast_transaction.id
     *
     * @return the value of broadcast_transaction.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broadcast_transaction.id
     *
     * @param id the value for broadcast_transaction.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broadcast_transaction.ref_id
     *
     * @return the value of broadcast_transaction.ref_id
     * @mbggenerated
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broadcast_transaction.ref_id
     *
     * @param refId the value for broadcast_transaction.ref_id
     * @mbggenerated
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broadcast_transaction.type
     *
     * @return the value of broadcast_transaction.type
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broadcast_transaction.type
     *
     * @param type the value for broadcast_transaction.type
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broadcast_transaction.v
     *
     * @return the value of broadcast_transaction.v
     * @mbggenerated
     */
    public Integer getV() {
        return v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broadcast_transaction.v
     *
     * @param v the value for broadcast_transaction.v
     * @mbggenerated
     */
    public void setV(Integer v) {
        this.v = v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broadcast_transaction.r
     *
     * @return the value of broadcast_transaction.r
     * @mbggenerated
     */
    public String getR() {
        return r;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broadcast_transaction.r
     *
     * @param r the value for broadcast_transaction.r
     * @mbggenerated
     */
    public void setR(String r) {
        this.r = r == null ? null : r.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broadcast_transaction.s
     *
     * @return the value of broadcast_transaction.s
     * @mbggenerated
     */
    public String getS() {
        return s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broadcast_transaction.s
     *
     * @param s the value for broadcast_transaction.s
     * @mbggenerated
     */
    public void setS(String s) {
        this.s = s == null ? null : s.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broadcast_transaction.signed_data
     *
     * @return the value of broadcast_transaction.signed_data
     * @mbggenerated
     */
    public String getSignedData() {
        return signedData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broadcast_transaction.signed_data
     *
     * @param signedData the value for broadcast_transaction.signed_data
     * @mbggenerated
     */
    public void setSignedData(String signedData) {
        this.signedData = signedData == null ? null : signedData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broadcast_transaction.status
     *
     * @return the value of broadcast_transaction.status
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broadcast_transaction.status
     *
     * @param status the value for broadcast_transaction.status
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broadcast_transaction.tx_hash
     *
     * @return the value of broadcast_transaction.tx_hash
     * @mbggenerated
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broadcast_transaction.tx_hash
     *
     * @param txHash the value for broadcast_transaction.tx_hash
     * @mbggenerated
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash == null ? null : txHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broadcast_transaction.add_time
     *
     * @return the value of broadcast_transaction.add_time
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broadcast_transaction.add_time
     *
     * @param addTime the value for broadcast_transaction.add_time
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broadcast_transaction.update_time
     *
     * @return the value of broadcast_transaction.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broadcast_transaction.update_time
     *
     * @param updateTime the value for broadcast_transaction.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }
}