package com.ted.resonance.entity;

import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;

public class CaCashConfigBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_cash_config.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "配置表Id")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_cash_config.start_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "开始时间")
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_cash_config.end_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "结束时间")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_cash_config.eth_nums
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "ETH资金总量")
    private BigDecimal ethNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_cash_config.etc_nums
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "ETC资金总量")
    private BigDecimal etcNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_cash_config.del
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "记录状态 (0:有效，1：无效)")
    private Short del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_cash_config.create_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "创建时间")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_cash_config.update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "更新时间")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_cash_config.id
     *
     * @return the value of ca_cash_config.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_cash_config.id
     *
     * @param id the value for ca_cash_config.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_cash_config.start_time
     *
     * @return the value of ca_cash_config.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_cash_config.start_time
     *
     * @param startTime the value for ca_cash_config.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_cash_config.end_time
     *
     * @return the value of ca_cash_config.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_cash_config.end_time
     *
     * @param endTime the value for ca_cash_config.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_cash_config.eth_nums
     *
     * @return the value of ca_cash_config.eth_nums
     *
     * @mbggenerated
     */
    public BigDecimal getEthNums() {
        return ethNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_cash_config.eth_nums
     *
     * @param ethNums the value for ca_cash_config.eth_nums
     *
     * @mbggenerated
     */
    public void setEthNums(BigDecimal ethNums) {
        this.ethNums = ethNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_cash_config.etc_nums
     *
     * @return the value of ca_cash_config.etc_nums
     *
     * @mbggenerated
     */
    public BigDecimal getEtcNums() {
        return etcNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_cash_config.etc_nums
     *
     * @param etcNums the value for ca_cash_config.etc_nums
     *
     * @mbggenerated
     */
    public void setEtcNums(BigDecimal etcNums) {
        this.etcNums = etcNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_cash_config.del
     *
     * @return the value of ca_cash_config.del
     *
     * @mbggenerated
     */
    public Short getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_cash_config.del
     *
     * @param del the value for ca_cash_config.del
     *
     * @mbggenerated
     */
    public void setDel(Short del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_cash_config.create_time
     *
     * @return the value of ca_cash_config.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_cash_config.create_time
     *
     * @param createTime the value for ca_cash_config.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_cash_config.update_time
     *
     * @return the value of ca_cash_config.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_cash_config.update_time
     *
     * @param updateTime the value for ca_cash_config.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}