package com.ted.resonance.entity;

import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;

public class CaCollarCouponsBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "领金券Id")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "机会表ID")
    private Long drawId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.user_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "用户ID")
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.tx_hash
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "hash值")
    private String txHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.addr
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "地址信息")
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.pay_coin_type
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "支付的币种类型 ETH/ETC")
    private String payCoinType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.pay_coin_nums
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "需要支付的主链币个数")
    private BigDecimal payCoinNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.pay_ted_nums
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "需要支付的TED个数")
    private BigDecimal payTedNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.reward_coin_type
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "奖励的主链币种类型(ETH/ETC)")
    private String rewardCoinType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.reward_coin_nums
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "奖励的主链币种个数")
    private BigDecimal rewardCoinNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.earning_rate
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "收益率(%)")
    private Long earningRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.reward_status
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "状态（1:待领取, 2:已领取, 3:使用中, 4:已使用, 5:已过期）")
    private String rewardStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.reward_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "领取时间（开始时间）")
    private Date rewardTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.expires_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "失效时间")
    private Date expiresTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.create_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "创建时间")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.del
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "0：有效  1：无效")
    private Short del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_collar_coupons.remark
     *
     * @mbggenerated
     */
    @ApiModelProperty(notes = "备注")
    private String remark;

    //新增字段
    private BigDecimal ethRate; //用户抽奖获取领金券 需要支付的矿工费

    public BigDecimal getEthRate() {
        return ethRate;
    }

    public void setEthRate(BigDecimal ethRate) {
        this.ethRate = ethRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.id
     *
     * @return the value of ca_collar_coupons.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.id
     *
     * @param id the value for ca_collar_coupons.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.user_id
     *
     * @return the value of ca_collar_coupons.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.user_id
     *
     * @param userId the value for ca_collar_coupons.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.tx_hash
     *
     * @return the value of ca_collar_coupons.tx_hash
     *
     * @mbggenerated
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.tx_hash
     *
     * @param txHash the value for ca_collar_coupons.tx_hash
     *
     * @mbggenerated
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash == null ? null : txHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.addr
     *
     * @return the value of ca_collar_coupons.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.addr
     *
     * @param addr the value for ca_collar_coupons.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.pay_coin_type
     *
     * @return the value of ca_collar_coupons.pay_coin_type
     *
     * @mbggenerated
     */
    public String getPayCoinType() {
        return payCoinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.pay_coin_type
     *
     * @param payCoinType the value for ca_collar_coupons.pay_coin_type
     *
     * @mbggenerated
     */
    public void setPayCoinType(String payCoinType) {
        this.payCoinType = payCoinType == null ? null : payCoinType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.pay_coin_nums
     *
     * @return the value of ca_collar_coupons.pay_coin_nums
     *
     * @mbggenerated
     */
    public BigDecimal getPayCoinNums() {
        return payCoinNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.pay_coin_nums
     *
     * @param payCoinNums the value for ca_collar_coupons.pay_coin_nums
     *
     * @mbggenerated
     */
    public void setPayCoinNums(BigDecimal payCoinNums) {
        this.payCoinNums = payCoinNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.pay_ted_nums
     *
     * @return the value of ca_collar_coupons.pay_ted_nums
     *
     * @mbggenerated
     */
    public BigDecimal getPayTedNums() {
        return payTedNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.pay_ted_nums
     *
     * @param payTedNums the value for ca_collar_coupons.pay_ted_nums
     *
     * @mbggenerated
     */
    public void setPayTedNums(BigDecimal payTedNums) {
        this.payTedNums = payTedNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.reward_coin_type
     *
     * @return the value of ca_collar_coupons.reward_coin_type
     *
     * @mbggenerated
     */
    public String getRewardCoinType() {
        return rewardCoinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.reward_coin_type
     *
     * @param rewardCoinType the value for ca_collar_coupons.reward_coin_type
     *
     * @mbggenerated
     */
    public void setRewardCoinType(String rewardCoinType) {
        this.rewardCoinType = rewardCoinType == null ? null : rewardCoinType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.reward_coin_nums
     *
     * @return the value of ca_collar_coupons.reward_coin_nums
     *
     * @mbggenerated
     */
    public BigDecimal getRewardCoinNums() {
        return rewardCoinNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.reward_coin_nums
     *
     * @param rewardCoinNums the value for ca_collar_coupons.reward_coin_nums
     *
     * @mbggenerated
     */
    public void setRewardCoinNums(BigDecimal rewardCoinNums) {
        this.rewardCoinNums = rewardCoinNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.earning_rate
     *
     * @return the value of ca_collar_coupons.earning_rate
     *
     * @mbggenerated
     */
    public Long getEarningRate() {
        return earningRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.earning_rate
     *
     * @param earningRate the value for ca_collar_coupons.earning_rate
     *
     * @mbggenerated
     */
    public void setEarningRate(Long earningRate) {
        this.earningRate = earningRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.reward_status
     *
     * @return the value of ca_collar_coupons.reward_status
     *
     * @mbggenerated
     */
    public String getRewardStatus() {
        return rewardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.reward_status
     *
     * @param rewardStatus the value for ca_collar_coupons.reward_status
     *
     * @mbggenerated
     */
    public void setRewardStatus(String rewardStatus) {
        this.rewardStatus = rewardStatus == null ? null : rewardStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.reward_time
     *
     * @return the value of ca_collar_coupons.reward_time
     *
     * @mbggenerated
     */
    public Date getRewardTime() {
        return rewardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.reward_time
     *
     * @param rewardTime the value for ca_collar_coupons.reward_time
     *
     * @mbggenerated
     */
    public void setRewardTime(Date rewardTime) {
        this.rewardTime = rewardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.expires_time
     *
     * @return the value of ca_collar_coupons.expires_time
     *
     * @mbggenerated
     */
    public Date getExpiresTime() {
        return expiresTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.expires_time
     *
     * @param expiresTime the value for ca_collar_coupons.expires_time
     *
     * @mbggenerated
     */
    public void setExpiresTime(Date expiresTime) {
        this.expiresTime = expiresTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.create_time
     *
     * @return the value of ca_collar_coupons.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.create_time
     *
     * @param createTime the value for ca_collar_coupons.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.update_time
     *
     * @return the value of ca_collar_coupons.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.update_time
     *
     * @param updateTime the value for ca_collar_coupons.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.del
     *
     * @return the value of ca_collar_coupons.del
     *
     * @mbggenerated
     */
    public Short getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.del
     *
     * @param del the value for ca_collar_coupons.del
     *
     * @mbggenerated
     */
    public void setDel(Short del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_collar_coupons.remark
     *
     * @return the value of ca_collar_coupons.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_collar_coupons.remark
     *
     * @param remark the value for ca_collar_coupons.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public Long getDrawId() {
        return drawId;
    }

    public void setDrawId(Long drawId) {
        this.drawId = drawId;
    }
}