package com.ted.resonance.entity;

import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;

public class CaDrawChanceBean {
    private Long id;
    private String userId;
    @ApiModelProperty(notes = "地址")
    private String addr;
    @ApiModelProperty(notes = "机会有效开始时间")
    private Date startTime;
    @ApiModelProperty(notes = "机会失效时间")
    private Date expiresTime;
    private Date createTime;
    private Date updateTime;
    @ApiModelProperty(notes = "抽奖机会次数")
    private Integer chanceTimes;
    @ApiModelProperty(notes = "领取状态（1:未领取, 2:已领取）")
    private Integer drawStatus;
    private Short del;
    private String remark;

    //新增字段
    private BigDecimal balance; //根据用户地址获取的用户TED(TCH)余额

    private int rewardTimes; //根据用户余额获取用户的第二天将获取的抽奖次数

    public BigDecimal getBalance() {
        return balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public int getRewardTimes() {
        return rewardTimes;
    }

    public void setRewardTimes(int rewardTimes) {
        this.rewardTimes = rewardTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_draw_chance.id
     *
     * @return the value of ca_draw_chance.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_draw_chance.id
     *
     * @param id the value for ca_draw_chance.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_draw_chance.user_id
     *
     * @return the value of ca_draw_chance.user_id
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_draw_chance.user_id
     *
     * @param userId the value for ca_draw_chance.user_id
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_draw_chance.addr
     *
     * @return the value of ca_draw_chance.addr
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_draw_chance.addr
     *
     * @param addr the value for ca_draw_chance.addr
     * @mbggenerated
     */

    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_draw_chance.start_time
     *
     * @return the value of ca_draw_chance.start_time
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_draw_chance.start_time
     *
     * @param startTime the value for ca_draw_chance.start_time
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_draw_chance.expires_time
     *
     * @return the value of ca_draw_chance.expires_time
     * @mbggenerated
     */
    public Date getExpiresTime() {
        return expiresTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_draw_chance.expires_time
     *
     * @param expiresTime the value for ca_draw_chance.expires_time
     * @mbggenerated
     */
    public void setExpiresTime(Date expiresTime) {
        this.expiresTime = expiresTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_draw_chance.create_time
     *
     * @return the value of ca_draw_chance.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_draw_chance.create_time
     *
     * @param createTime the value for ca_draw_chance.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_draw_chance.update_time
     *
     * @return the value of ca_draw_chance.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_draw_chance.update_time
     *
     * @param updateTime the value for ca_draw_chance.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_draw_chance.chance_times
     *
     * @return the value of ca_draw_chance.chance_times
     * @mbggenerated
     */
    public Integer getChanceTimes() {
        return chanceTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_draw_chance.chance_times
     *
     * @param chanceTimes the value for ca_draw_chance.chance_times
     * @mbggenerated
     */
    public void setChanceTimes(Integer chanceTimes) {
        this.chanceTimes = chanceTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_draw_chance.draw_status
     *
     * @return the value of ca_draw_chance.draw_status
     * @mbggenerated
     */
    public Integer getDrawStatus() {
        return drawStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_draw_chance.draw_status
     *
     * @param drawStatus the value for ca_draw_chance.draw_status
     * @mbggenerated
     */
    public void setDrawStatus(Integer drawStatus) {
        this.drawStatus = drawStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_draw_chance.del
     *
     * @return the value of ca_draw_chance.del
     * @mbggenerated
     */
    public Short getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_draw_chance.del
     *
     * @param del the value for ca_draw_chance.del
     * @mbggenerated
     */
    public void setDel(Short del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_draw_chance.remark
     *
     * @return the value of ca_draw_chance.remark
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_draw_chance.remark
     *
     * @param remark the value for ca_draw_chance.remark
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}