package com.ted.resonance.entity;

import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

public class CaRecordInfoBean {

    // ID
    @ApiModelProperty(notes = "记录ID")
    private Long id;
    // 用户ID account表
    private Integer userId;
    @ApiModelProperty(notes = "地址")
    private String addr;
    @ApiModelProperty(notes = "炼金师加入时间")
    private Date incomeTime;
    // 修改时间
    private Date updateTime;
    //最小值时间更新标识
    private Date dayTime;
    // 0, 有效  1，无效
    private Short del;
    // 备注
    private String remark;

    public Date getDayTime() {
        return dayTime;
    }

    public void setDayTime(Date dayTime) {
        this.dayTime = dayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_record_info.id
     *
     * @return the value of ca_record_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_record_info.id
     *
     * @param id the value for ca_record_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_record_info.user_id
     *
     * @return the value of ca_record_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_record_info.user_id
     *
     * @param userId the value for ca_record_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_record_info.addr
     *
     * @return the value of ca_record_info.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_record_info.addr
     *
     * @param addr the value for ca_record_info.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_record_info.income_time
     *
     * @return the value of ca_record_info.income_time
     *
     * @mbggenerated
     */
    public Date getIncomeTime() {
        return incomeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_record_info.income_time
     *
     * @param incomeTime the value for ca_record_info.income_time
     *
     * @mbggenerated
     */
    public void setIncomeTime(Date incomeTime) {
        this.incomeTime = incomeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_record_info.update_time
     *
     * @return the value of ca_record_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_record_info.update_time
     *
     * @param updateTime the value for ca_record_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_record_info.del
     *
     * @return the value of ca_record_info.del
     *
     * @mbggenerated
     */
    public Short getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_record_info.del
     *
     * @param del the value for ca_record_info.del
     *
     * @mbggenerated
     */
    public void setDel(Short del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_record_info.remark
     *
     * @return the value of ca_record_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_record_info.remark
     *
     * @param remark the value for ca_record_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}