package com.ted.resonance.entity;

public class DataDictBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.category
     *
     * @mbggenerated
     */
    private Boolean category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.type
     *
     * @mbggenerated
     */
    private Boolean type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.key
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.enabled
     *
     * @mbggenerated
     */
    private String enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.id
     *
     * @return the value of data_dict.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.id
     *
     * @param id the value for data_dict.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.category
     *
     * @return the value of data_dict.category
     *
     * @mbggenerated
     */
    public Boolean getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.category
     *
     * @param category the value for data_dict.category
     *
     * @mbggenerated
     */
    public void setCategory(Boolean category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.type
     *
     * @return the value of data_dict.type
     *
     * @mbggenerated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.type
     *
     * @param type the value for data_dict.type
     *
     * @mbggenerated
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.key
     *
     * @return the value of data_dict.key
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.key
     *
     * @param key the value for data_dict.key
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.value
     *
     * @return the value of data_dict.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.value
     *
     * @param value the value for data_dict.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.enabled
     *
     * @return the value of data_dict.enabled
     *
     * @mbggenerated
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.enabled
     *
     * @param enabled the value for data_dict.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }
}