package com.ted.resonance.entity;

import java.util.Date;

public class ExActivityAdditionBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_activity_addition.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_activity_addition.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_activity_addition.begin_block
     *
     * @mbggenerated
     */
    private Integer beginBlock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_activity_addition.end_block
     *
     * @mbggenerated
     */
    private Integer endBlock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_activity_addition.addition_rate
     *
     * @mbggenerated
     */
    private Double additionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_activity_addition.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_activity_addition.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_activity_addition.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_activity_addition.id
     *
     * @return the value of ex_activity_addition.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_activity_addition.id
     *
     * @param id the value for ex_activity_addition.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_activity_addition.activity_id
     *
     * @return the value of ex_activity_addition.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_activity_addition.activity_id
     *
     * @param activityId the value for ex_activity_addition.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_activity_addition.begin_block
     *
     * @return the value of ex_activity_addition.begin_block
     *
     * @mbggenerated
     */
    public Integer getBeginBlock() {
        return beginBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_activity_addition.begin_block
     *
     * @param beginBlock the value for ex_activity_addition.begin_block
     *
     * @mbggenerated
     */
    public void setBeginBlock(Integer beginBlock) {
        this.beginBlock = beginBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_activity_addition.end_block
     *
     * @return the value of ex_activity_addition.end_block
     *
     * @mbggenerated
     */
    public Integer getEndBlock() {
        return endBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_activity_addition.end_block
     *
     * @param endBlock the value for ex_activity_addition.end_block
     *
     * @mbggenerated
     */
    public void setEndBlock(Integer endBlock) {
        this.endBlock = endBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_activity_addition.addition_rate
     *
     * @return the value of ex_activity_addition.addition_rate
     *
     * @mbggenerated
     */
    public Double getAdditionRate() {
        return additionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_activity_addition.addition_rate
     *
     * @param additionRate the value for ex_activity_addition.addition_rate
     *
     * @mbggenerated
     */
    public void setAdditionRate(Double additionRate) {
        this.additionRate = additionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_activity_addition.create_time
     *
     * @return the value of ex_activity_addition.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_activity_addition.create_time
     *
     * @param createTime the value for ex_activity_addition.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_activity_addition.update_time
     *
     * @return the value of ex_activity_addition.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_activity_addition.update_time
     *
     * @param updateTime the value for ex_activity_addition.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_activity_addition.is_deleted
     *
     * @return the value of ex_activity_addition.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_activity_addition.is_deleted
     *
     * @param isDeleted the value for ex_activity_addition.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}