package com.ted.resonance.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ExCfgActivityBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.begin_block
     *
     * @mbggenerated
     */
    private Integer beginBlock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.end_block
     *
     * @mbggenerated
     */
    private Integer endBlock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.period
     *
     * @mbggenerated
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.eth
     *
     * @mbggenerated
     */
    private BigDecimal eth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.etc
     *
     * @mbggenerated
     */
    private BigDecimal etc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_cfg_activity.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.id
     *
     * @return the value of ex_cfg_activity.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.id
     *
     * @param id the value for ex_cfg_activity.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.name
     *
     * @return the value of ex_cfg_activity.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.name
     *
     * @param name the value for ex_cfg_activity.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.begin_block
     *
     * @return the value of ex_cfg_activity.begin_block
     *
     * @mbggenerated
     */
    public Integer getBeginBlock() {
        return beginBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.begin_block
     *
     * @param beginBlock the value for ex_cfg_activity.begin_block
     *
     * @mbggenerated
     */
    public void setBeginBlock(Integer beginBlock) {
        this.beginBlock = beginBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.end_block
     *
     * @return the value of ex_cfg_activity.end_block
     *
     * @mbggenerated
     */
    public Integer getEndBlock() {
        return endBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.end_block
     *
     * @param endBlock the value for ex_cfg_activity.end_block
     *
     * @mbggenerated
     */
    public void setEndBlock(Integer endBlock) {
        this.endBlock = endBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.period
     *
     * @return the value of ex_cfg_activity.period
     *
     * @mbggenerated
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.period
     *
     * @param period the value for ex_cfg_activity.period
     *
     * @mbggenerated
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.eth
     *
     * @return the value of ex_cfg_activity.eth
     *
     * @mbggenerated
     */
    public BigDecimal getEth() {
        return eth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.eth
     *
     * @param eth the value for ex_cfg_activity.eth
     *
     * @mbggenerated
     */
    public void setEth(BigDecimal eth) {
        this.eth = eth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.etc
     *
     * @return the value of ex_cfg_activity.etc
     *
     * @mbggenerated
     */
    public BigDecimal getEtc() {
        return etc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.etc
     *
     * @param etc the value for ex_cfg_activity.etc
     *
     * @mbggenerated
     */
    public void setEtc(BigDecimal etc) {
        this.etc = etc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.status
     *
     * @return the value of ex_cfg_activity.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.status
     *
     * @param status the value for ex_cfg_activity.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.remark
     *
     * @return the value of ex_cfg_activity.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.remark
     *
     * @param remark the value for ex_cfg_activity.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.create_time
     *
     * @return the value of ex_cfg_activity.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.create_time
     *
     * @param createTime the value for ex_cfg_activity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.update_time
     *
     * @return the value of ex_cfg_activity.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.update_time
     *
     * @param updateTime the value for ex_cfg_activity.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_cfg_activity.del
     *
     * @return the value of ex_cfg_activity.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_cfg_activity.del
     *
     * @param del the value for ex_cfg_activity.del
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }
}