package com.ted.resonance.entity;

import com.ted.resonance.config.Translator;
import com.ted.resonance.enums.OrderStatus;
import com.ted.resonance.enums.TradeType;
import com.ted.resonance.utils.ParamValidUtil;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;

public class UserAccDetailBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.id
     *
     * @mbggenerated
     */
    @ApiModelProperty("主键ID")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.user_id
     *
     * @mbggenerated
     */
    @ApiModelProperty("用户ID")
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.addr
     *
     * @mbggenerated
     */
    @ApiModelProperty("用户地址")
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.acc_id
     *
     * @mbggenerated
     */

    @ApiModelProperty("账户ID")
    private Long accId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.trade_no
     *
     * @mbggenerated
     */
    @ApiModelProperty("账户ID")
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.coin_type
     *
     * @mbggenerated
     */
    @ApiModelProperty("币种")
    private String coinType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.amount
     *
     * @mbggenerated
     */
    @ApiModelProperty("交易金额")
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.pre_amount
     *
     * @mbggenerated
     */
    @ApiModelProperty("交易前金额")
    private BigDecimal preAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.after_amount
     *
     * @mbggenerated
     */
    @ApiModelProperty("交易后金额")
    private BigDecimal afterAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.fee
     *
     * @mbggenerated
     */
    @ApiModelProperty("手续费用")
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.trade_type
     *
     * @mbggenerated
     */
    @ApiModelProperty("REWARD, WITHDRAW")
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.trade_status
     *
     * @mbggenerated
     */
    @ApiModelProperty("交易状态   SUCCESS,FAIL,WITHDRAWING")
    private String tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.operate_type
     *
     * @mbggenerated
     */
    @ApiModelProperty("操作类型枚举 ADD:加 SUB: 减法")
    private String operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc_detail.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.id
     *
     * @return the value of user_acc_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.id
     *
     * @param id the value for user_acc_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.user_id
     *
     * @return the value of user_acc_detail.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.user_id
     *
     * @param userId the value for user_acc_detail.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.addr
     *
     * @return the value of user_acc_detail.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.addr
     *
     * @param addr the value for user_acc_detail.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.acc_id
     *
     * @return the value of user_acc_detail.acc_id
     *
     * @mbggenerated
     */
    public Long getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.acc_id
     *
     * @param accId the value for user_acc_detail.acc_id
     *
     * @mbggenerated
     */
    public void setAccId(Long accId) {
        this.accId = accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.trade_no
     *
     * @return the value of user_acc_detail.trade_no
     *
     * @mbggenerated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.trade_no
     *
     * @param tradeNo the value for user_acc_detail.trade_no
     *
     * @mbggenerated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.coin_type
     *
     * @return the value of user_acc_detail.coin_type
     *
     * @mbggenerated
     */
    public String getCoinType() {
        return coinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.coin_type
     *
     * @param coinType the value for user_acc_detail.coin_type
     *
     * @mbggenerated
     */
    public void setCoinType(String coinType) {
        this.coinType = coinType == null ? null : coinType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.amount
     *
     * @return the value of user_acc_detail.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.amount
     *
     * @param amount the value for user_acc_detail.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.pre_amount
     *
     * @return the value of user_acc_detail.pre_amount
     *
     * @mbggenerated
     */
    public BigDecimal getPreAmount() {
        return preAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.pre_amount
     *
     * @param preAmount the value for user_acc_detail.pre_amount
     *
     * @mbggenerated
     */
    public void setPreAmount(BigDecimal preAmount) {
        this.preAmount = preAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.after_amount
     *
     * @return the value of user_acc_detail.after_amount
     *
     * @mbggenerated
     */
    public BigDecimal getAfterAmount() {
        return afterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.after_amount
     *
     * @param afterAmount the value for user_acc_detail.after_amount
     *
     * @mbggenerated
     */
    public void setAfterAmount(BigDecimal afterAmount) {
        this.afterAmount = afterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.fee
     *
     * @return the value of user_acc_detail.fee
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.fee
     *
     * @param fee the value for user_acc_detail.fee
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.trade_type
     *
     * @return the value of user_acc_detail.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        if("WITHDRAW".equals(tradeType)){
            if(ParamValidUtil.validParams(tradeStatus)){
                tradeType = Translator.toLocale(tradeType+"_"+tradeStatus);
            }else{
                tradeType = Translator.toLocale(tradeType);
            }
        }else{
            tradeType = Translator.toLocale(tradeType);
        }

        return tradeType;

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.trade_type
     *
     * @param tradeType the value for user_acc_detail.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.trade_status
     *
     * @return the value of user_acc_detail.trade_status
     *
     * @mbggenerated
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.trade_status
     *
     * @param tradeStatus the value for user_acc_detail.trade_status
     *
     * @mbggenerated
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus == null ? null : tradeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.operate_type
     *
     * @return the value of user_acc_detail.operate_type
     *
     * @mbggenerated
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.operate_type
     *
     * @param operateType the value for user_acc_detail.operate_type
     *
     * @mbggenerated
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.create_time
     *
     * @return the value of user_acc_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.create_time
     *
     * @param createTime the value for user_acc_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.update_time
     *
     * @return the value of user_acc_detail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.update_time
     *
     * @param updateTime the value for user_acc_detail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.remark
     *
     * @return the value of user_acc_detail.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.remark
     *
     * @param remark the value for user_acc_detail.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc_detail.is_deleted
     *
     * @return the value of user_acc_detail.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc_detail.is_deleted
     *
     * @param isDeleted the value for user_acc_detail.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}