package com.ted.resonance.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserAccBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc.user_id
     *
     * @mbggenerated
     */
    private Long userId;


    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc.coin_type
     *
     * @mbggenerated
     */
    private String coinType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc.frozen_amount
     *
     * @mbggenerated
     */
    private BigDecimal frozenAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_acc.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc.id
     *
     * @return the value of user_acc.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc.id
     *
     * @param id the value for user_acc.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc.user_id
     *
     * @return the value of user_acc.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc.user_id
     *
     * @param userId the value for user_acc.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc.coin_type
     *
     * @return the value of user_acc.coin_type
     *
     * @mbggenerated
     */
    public String getCoinType() {
        return coinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc.coin_type
     *
     * @param coinType the value for user_acc.coin_type
     *
     * @mbggenerated
     */
    public void setCoinType(String coinType) {
        this.coinType = coinType == null ? null : coinType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc.balance
     *
     * @return the value of user_acc.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc.balance
     *
     * @param balance the value for user_acc.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc.frozen_amount
     *
     * @return the value of user_acc.frozen_amount
     *
     * @mbggenerated
     */
    public BigDecimal getFrozenAmount() {
        return frozenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc.frozen_amount
     *
     * @param frozenAmount the value for user_acc.frozen_amount
     *
     * @mbggenerated
     */
    public void setFrozenAmount(BigDecimal frozenAmount) {
        this.frozenAmount = frozenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc.create_time
     *
     * @return the value of user_acc.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc.create_time
     *
     * @param createTime the value for user_acc.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc.update_time
     *
     * @return the value of user_acc.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc.update_time
     *
     * @param updateTime the value for user_acc.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_acc.is_deleted
     *
     * @return the value of user_acc.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_acc.is_deleted
     *
     * @param isDeleted the value for user_acc.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }


    public String getAddr() {
        return addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }
}