package com.ted.resonance.entity;

import java.math.BigDecimal;
import java.util.Date;

public class WithdrawOrderRecordBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.trade_no
     *
     * @mbggenerated
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.currency
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.address_to
     *
     * @mbggenerated
     */
    private String addressTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.fee
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.fee_currency
     *
     * @mbggenerated
     */
    private String feeCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.auto_approve
     *
     * @mbggenerated
     */
    private Boolean autoApprove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.address_from
     *
     * @mbggenerated
     */
    private String addressFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.tx_id
     *
     * @mbggenerated
     */
    private String txId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.parent_currency
     *
     * @mbggenerated
     */
    private String parentCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.operate_time
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.operator_id
     *
     * @mbggenerated
     */
    private String operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.contract_address
     *
     * @mbggenerated
     */
    private String contractAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.token
     *
     * @mbggenerated
     */
    private Boolean token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_order_record.wallet_id
     *
     * @mbggenerated
     */
    private String walletId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.id
     *
     * @return the value of withdraw_order_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.id
     *
     * @param id the value for withdraw_order_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.trade_no
     *
     * @return the value of withdraw_order_record.trade_no
     *
     * @mbggenerated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.trade_no
     *
     * @param tradeNo the value for withdraw_order_record.trade_no
     *
     * @mbggenerated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.user_id
     *
     * @return the value of withdraw_order_record.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.user_id
     *
     * @param userId the value for withdraw_order_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.currency
     *
     * @return the value of withdraw_order_record.currency
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.currency
     *
     * @param currency the value for withdraw_order_record.currency
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.amount
     *
     * @return the value of withdraw_order_record.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.amount
     *
     * @param amount the value for withdraw_order_record.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.address_to
     *
     * @return the value of withdraw_order_record.address_to
     *
     * @mbggenerated
     */
    public String getAddressTo() {
        return addressTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.address_to
     *
     * @param addressTo the value for withdraw_order_record.address_to
     *
     * @mbggenerated
     */
    public void setAddressTo(String addressTo) {
        this.addressTo = addressTo == null ? null : addressTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.fee
     *
     * @return the value of withdraw_order_record.fee
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.fee
     *
     * @param fee the value for withdraw_order_record.fee
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.fee_currency
     *
     * @return the value of withdraw_order_record.fee_currency
     *
     * @mbggenerated
     */
    public String getFeeCurrency() {
        return feeCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.fee_currency
     *
     * @param feeCurrency the value for withdraw_order_record.fee_currency
     *
     * @mbggenerated
     */
    public void setFeeCurrency(String feeCurrency) {
        this.feeCurrency = feeCurrency == null ? null : feeCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.status
     *
     * @return the value of withdraw_order_record.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.status
     *
     * @param status the value for withdraw_order_record.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.add_time
     *
     * @return the value of withdraw_order_record.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.add_time
     *
     * @param addTime the value for withdraw_order_record.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.update_time
     *
     * @return the value of withdraw_order_record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.update_time
     *
     * @param updateTime the value for withdraw_order_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.auto_approve
     *
     * @return the value of withdraw_order_record.auto_approve
     *
     * @mbggenerated
     */
    public Boolean getAutoApprove() {
        return autoApprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.auto_approve
     *
     * @param autoApprove the value for withdraw_order_record.auto_approve
     *
     * @mbggenerated
     */
    public void setAutoApprove(Boolean autoApprove) {
        this.autoApprove = autoApprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.address_from
     *
     * @return the value of withdraw_order_record.address_from
     *
     * @mbggenerated
     */
    public String getAddressFrom() {
        return addressFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.address_from
     *
     * @param addressFrom the value for withdraw_order_record.address_from
     *
     * @mbggenerated
     */
    public void setAddressFrom(String addressFrom) {
        this.addressFrom = addressFrom == null ? null : addressFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.tx_id
     *
     * @return the value of withdraw_order_record.tx_id
     *
     * @mbggenerated
     */
    public String getTxId() {
        return txId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.tx_id
     *
     * @param txId the value for withdraw_order_record.tx_id
     *
     * @mbggenerated
     */
    public void setTxId(String txId) {
        this.txId = txId == null ? null : txId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.type
     *
     * @return the value of withdraw_order_record.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.type
     *
     * @param type the value for withdraw_order_record.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.username
     *
     * @return the value of withdraw_order_record.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.username
     *
     * @param username the value for withdraw_order_record.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.parent_currency
     *
     * @return the value of withdraw_order_record.parent_currency
     *
     * @mbggenerated
     */
    public String getParentCurrency() {
        return parentCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.parent_currency
     *
     * @param parentCurrency the value for withdraw_order_record.parent_currency
     *
     * @mbggenerated
     */
    public void setParentCurrency(String parentCurrency) {
        this.parentCurrency = parentCurrency == null ? null : parentCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.operate_time
     *
     * @return the value of withdraw_order_record.operate_time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.operate_time
     *
     * @param operateTime the value for withdraw_order_record.operate_time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    public String getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.contract_address
     *
     * @return the value of withdraw_order_record.contract_address
     *
     * @mbggenerated
     */
    public String getContractAddress() {
        return contractAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.contract_address
     *
     * @param contractAddress the value for withdraw_order_record.contract_address
     *
     * @mbggenerated
     */
    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress == null ? null : contractAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.token
     *
     * @return the value of withdraw_order_record.token
     *
     * @mbggenerated
     */
    public Boolean getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.token
     *
     * @param token the value for withdraw_order_record.token
     *
     * @mbggenerated
     */
    public void setToken(Boolean token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.remark
     *
     * @return the value of withdraw_order_record.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.remark
     *
     * @param remark the value for withdraw_order_record.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.memo
     *
     * @return the value of withdraw_order_record.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.memo
     *
     * @param memo the value for withdraw_order_record.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_order_record.wallet_id
     *
     * @return the value of withdraw_order_record.wallet_id
     *
     * @mbggenerated
     */
    public String getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_order_record.wallet_id
     *
     * @param walletId the value for withdraw_order_record.wallet_id
     *
     * @mbggenerated
     */
    public void setWalletId(String walletId) {
        this.walletId = walletId == null ? null : walletId.trim();
    }
}