package com.ted.resonance.mapper;

import com.ted.resonance.entity.AddressMinBalanceBean;
import org.apache.ibatis.annotations.Mapper;

import java.util.Date;
import java.util.List;

@Mapper
public interface AddressMinBalanceBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_min_balance
     *
     * @mbggenerated
     */
    int insert(AddressMinBalanceBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_min_balance
     *
     * @mbggenerated
     */
    int insertSelective(AddressMinBalanceBean record);

    /**
     * 根据日期查找
     *
     * @param dayTime
     * @return
     */
    List<AddressMinBalanceBean> selectByDayTime(Date dayTime);
}