package com.ted.resonance.mapper;

import com.ted.resonance.entity.BroadcastTransactionBean;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface BroadcastTransactionBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broadcast_transaction
     *
     * @mbggenerated
     */
    int insert(BroadcastTransactionBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broadcast_transaction
     *
     * @mbggenerated
     */
    int insertSelective(BroadcastTransactionBean record);

    BroadcastTransactionBean findByRefIdAndType(@Param("refId") Integer refId, @Param("type") String type);

    void updateById(@Param("id") Integer id, @Param("signedData") String signedData, @Param("txHash") String txHash, @Param("status") Integer status);

    List<BroadcastTransactionBean> findUnconfirm(@Param("skip") Integer skip, @Param("num") Integer num);

    List<BroadcastTransactionBean> findBroadcast(@Param("skip") Integer skip, @Param("num") Integer num);

}