package com.ted.resonance.mapper;

import com.ted.resonance.entity.CaCashConfigBean;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Mapper
public interface CaCashConfigBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_cash_config
     *
     * @mbggenerated
     */
    int insert(CaCashConfigBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_cash_config
     *
     * @mbggenerated
     */
    int insertSelective(CaCashConfigBean record);

    CaCashConfigBean selectByTime(Date time);
}