package com.ted.resonance.mapper;

import com.ted.resonance.entity.CaDrawChanceBean;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;

import javax.transaction.Transactional;

@Mapper
public interface CaDrawChanceBeanMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_draw_chance
     *
     * @mbggenerated
     */
    int insert(CaDrawChanceBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_draw_chance
     *
     * @mbggenerated
     */
    int insertSelective(CaDrawChanceBean record);

    /**
     * 查询当天的机会
     * @param startTime
     * @return
     */
    List<CaDrawChanceBean> selectByStartTime(Date startTime);



    CaDrawChanceBean findCaCollarCouponsByUserId(@Param("addr") String addr);

    @Update(value = "update ca_draw_chance set chance_times=chance_times-1  where id =#{id} and chance_times>0 ")
    int updateRewardStatus(@Param("id") Long id);

    /**
     * 批量插入or保存
     * @param caDrawChanceBeanList
     */
    void batchSaveOrUpdate(List<CaDrawChanceBean> caDrawChanceBeanList);
}