package com.ted.resonance.mapper;

import com.ted.resonance.entity.CaRecordInfoBean;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
public interface CaRecordInfoBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_record_info
     *
     * @mbggenerated
     */
    int insert(CaRecordInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_record_info
     *
     * @mbggenerated
     */
    int insertSelective(CaRecordInfoBean record);
}