package com.ted.resonance.mapper;

import com.ted.resonance.entity.DataDictBean;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface DataDictBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbggenerated
     */
    int insert(DataDictBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbggenerated
     */
    int insertSelective(DataDictBean record);


    DataDictBean queryByKey(@Param("key") String key);


    List<DataDictBean> queryAllDict();

}