package com.ted.resonance.mapper;

import com.ted.resonance.entity.ExCfgActivityBean;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ExCfgActivityBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_cfg_activity
     *
     * @mbggenerated
     */
    int insert(ExCfgActivityBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_cfg_activity
     *
     * @mbggenerated
     */
    int insertSelective(ExCfgActivityBean record);

    ExCfgActivityBean selectById(@Param("id") Long id);

    List<ExCfgActivityBean> queryListByStatus(@Param("status") List<Integer> status);

    void updateActivityStatus(@Param("id")Long id, @Param("status") Integer status);
}