package com.ted.resonance.mapper;


import com.ted.resonance.entity.TxBean;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TxBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx
     *
     * @mbggenerated
     */
    int insert(TxBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx
     *
     * @mbggenerated
     */
    int insertSelective(TxBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx
     *
     * @mbggenerated
     */
    TxBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TxBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TxBean record);

    TxBean selectByTxHash(@Param("txHash") String txHash);
}