package com.ted.resonance.mapper;

import com.ted.resonance.entity.UserAccDetailBean;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface UserAccDetailBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_acc_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_acc_detail
     *
     * @mbggenerated
     */
    int insert(UserAccDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_acc_detail
     *
     * @mbggenerated
     */
    int insertSelective(UserAccDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_acc_detail
     *
     * @mbggenerated
     */
    UserAccDetailBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_acc_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAccDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_acc_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAccDetailBean record);

    /**
     * 根据地址和币种类型查询详细的信息
     *
     * @param addr
     * @param coinType
     * @return
     */
    List<UserAccDetailBean> selectDetailByAddrAndCoinType(@Param("addr") String addr, @Param("coinType") String coinType);

    UserAccDetailBean selectByTradeNo(String tradeNo);

    int updateTradeStatusByNo(@Param("tradeNo") String tradeNo, @Param("tradeStatus") String tradeStatus);

}