package com.ted.resonance.mapper;

import com.ted.resonance.entity.UserAccBean;
import com.ted.resonance.entity.request.BalanceRequest;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

import java.math.BigDecimal;

@Mapper
public interface UserAccBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_acc
     *
     * @mbggenerated
     */
    int insert(UserAccBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_acc
     *
     * @mbggenerated
     */
    int insertSelective(UserAccBean record);

    //UserAccBean selectByUserIdAndCoin(@Param("userId") Long userId, @Param("coinType") String coinType);


    int forzenBalanceById(@Param("tradeAmount") BigDecimal tradeAmount, @Param("id")Long id);

    void addUserBalanceById(@Param("tradeAmount") BigDecimal tradeAmount, @Param("id")Long id);


    UserAccBean selectByAddrAndCoinType(@Param("addr") String addr, @Param("coinType") String coinType);

    int updateAddBalanceById(@Param("tradeAmount") BigDecimal tradeAmount, @Param("id") Long id);

    /**
     * 查询余额
     *
     * @param balanceRequest
     * @return
     */
    List<UserAccBean> selectBalances(BalanceRequest balanceRequest);
}