package com.ted.resonance.mapper;

import com.ted.resonance.entity.WithdrawOrderRecordBean;
import com.ted.resonance.enums.WithdrawOrderRecordStatusEnum;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.math.BigInteger;
import java.util.Date;
import java.util.List;

@Mapper
public interface WithdrawOrderRecordBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_order_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_order_record
     *
     * @mbggenerated
     */
    int insert(WithdrawOrderRecordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_order_record
     *
     * @mbggenerated
     */
    int insertSelective(WithdrawOrderRecordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_order_record
     *
     * @mbggenerated
     */
    WithdrawOrderRecordBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_order_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WithdrawOrderRecordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_order_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WithdrawOrderRecordBean record);

    WithdrawOrderRecordBean selectTradeNo(String tradeNo);

    int updateStatus(@Param("id") BigInteger id, @Param("status") WithdrawOrderRecordStatusEnum status, @Param("operatorId") String operatorId, @Param("operateTime") Date operateTime, @Param("remark") String remark);

    WithdrawOrderRecordBean findById(@Param("id") BigInteger id);

    WithdrawOrderRecordBean findByTradeNo(@Param("tradeNo") String tradeNo);

    List<WithdrawOrderRecordBean> findAll(@Param("userId") Integer userId, @Param("username") String username, @Param("address") String address
            , @Param("tradeNo") String tradeNo, @Param("txHash") String txHash,
                                          @Param("from") Date from, @Param("to") Date to,
                                          @Param("status") List<String> status, @Param("parentCurrency") String parentCurrency,
                                          @Param("currency") String currency);

    int updateStatusAndTx(@Param("id") BigInteger id, @Param("status") WithdrawOrderRecordStatusEnum status, @Param("txId") String txId, @Param("addressFrom") String addressFrom);

}